In [1]:
import pandas as pd

In [14]:
file = "Marketing Campaign Performance (Raw Dataset).xlsx"

campaigns = pd.read_excel(file, sheet_name = 'Campaigns')
campaigns.head()

,Campaign_ID,Campaign_Name,Channel,Objective,Start_Date,Budget,End_Date,Target_Audience
0,CMP1018,Always-On Promo 19,Meta Ads,Lead Generation,2025-07-09,84765.97,2025-09-12,25-34
1,CMP1045,Monsoon Promo 46,TikTok,Brand Awareness,2024-07-05,201851.99,2024-09-13,55+
2,CMP1047,Always-On Retargeting 48,YouTube,Conversions,2024-03-27,74545.09,2024-04-24,35-44
3,CMP1089,Always-On Awareness 90,LinkedIn,Lead Generation,2024-12-08,214875.41,2025-02-04,18-24
4,CMP1004,Festive Acquisition 5,YouTube,Conversions,2024-10-04,216529.45,2024-10-18,55+

In [15]:
# Identifying duplicate values

campaigns.duplicated().sum()

np.int64(3)

In [16]:
# Droping Duplicate Values
campaigns = campaigns.drop_duplicates()
campaigns

,Campaign_ID,Campaign_Name,Channel,Objective,Start_Date,Budget,End_Date,Target_Audience
0,CMP1018,Always-On Promo 19,Meta Ads,Lead Generation,2025-07-09,84765.97,2025-09-12,25-34
1,CMP1045,Monsoon Promo 46,TikTok,Brand Awareness,2024-07-05,201851.99,2024-09-13,55+
2,CMP1047,Always-On Retargeting 48,YouTube,Conversions,2024-03-27,74545.09,2024-04-24,35-44
3,CMP1089,Always-On Awareness 90,LinkedIn,Lead Generation,2024-12-08,214875.41,2025-02-04,18-24
4,CMP1004,Festive Acquisition 5,YouTube,Conversions,2024-10-04,216529.45,2024-10-18,55+
...,...,...,...,...,...,...,...,...
118,CMP1106,New Year Awareness 107,TikTok,Conversions,2025-02-17,81718.48,2025-05-16,55+
119,CMP1014,Diwali Awareness 15,YouTube,Traffic,2024-06-22,101102.23,2024-07-28,18-24
120,CMP1092,Monsoon Awareness 93,Instagram,Lead Generation,2024-06-18,153240.63,2024-07-21,35-44
121,CMP1051,New Year Acquisition 52,Meta Ads,Conversions,2024-04-09,55253.46,2024-06-16,45-54
122,CMP1102,Monsoon Retargeting 103,YouTube,Brand Awareness,2024-03-05,198604.10,2024-05-28,18-24

In [17]:
campaigns.duplicated().sum()

np.int64(0)

In [18]:
# Identifying missing values

campaigns.isnull().sum()

Campaign_ID        0
Campaign_Name      0
Channel            0
Objective          1
Start_Date         0
Budget             1
End_Date           0
Target_Audience    1
dtype: int64

In [19]:
# Handiling missing values

campaigns['Objective'] = campaigns['Objective'].fillna(campaigns['Objective'].mode()[0])

campaigns['Budget'] = campaigns['Budget'].fillna(campaigns['Budget'].median())

campaigns['Target_Audience'] = campaigns['Target_Audience'].fillna(campaigns['Target_Audience'].mode()[0])

campaigns

,Campaign_ID,Campaign_Name,Channel,Objective,Start_Date,Budget,End_Date,Target_Audience
0,CMP1018,Always-On Promo 19,Meta Ads,Lead Generation,2025-07-09,84765.97,2025-09-12,25-34
1,CMP1045,Monsoon Promo 46,TikTok,Brand Awareness,2024-07-05,201851.99,2024-09-13,55+
2,CMP1047,Always-On Retargeting 48,YouTube,Conversions,2024-03-27,74545.09,2024-04-24,35-44
3,CMP1089,Always-On Awareness 90,LinkedIn,Lead Generation,2024-12-08,214875.41,2025-02-04,18-24
4,CMP1004,Festive Acquisition 5,YouTube,Conversions,2024-10-04,216529.45,2024-10-18,55+
...,...,...,...,...,...,...,...,...
118,CMP1106,New Year Awareness 107,TikTok,Conversions,2025-02-17,81718.48,2025-05-16,55+
119,CMP1014,Diwali Awareness 15,YouTube,Traffic,2024-06-22,101102.23,2024-07-28,18-24
120,CMP1092,Monsoon Awareness 93,Instagram,Lead Generation,2024-06-18,153240.63,2024-07-21,35-44
121,CMP1051,New Year Acquisition 52,Meta Ads,Conversions,2024-04-09,55253.46,2024-06-16,45-54
122,CMP1102,Monsoon Retargeting 103,YouTube,Brand Awareness,2024-03-05,198604.10,2024-05-28,18-24

In [20]:
campaigns.isnull().sum()

Campaign_ID        0
Campaign_Name      0
Channel            0
Objective          0
Start_Date         0
Budget             0
End_Date           0
Target_Audience    0
dtype: int64

In [21]:
# Converting Dates into DateTime

campaigns['Start_Date'] = pd.to_datetime(campaigns['Start_Date'])

campaigns['End_Date'] = pd.to_datetime(campaigns['End_Date'])
campaigns

,Campaign_ID,Campaign_Name,Channel,Objective,Start_Date,Budget,End_Date,Target_Audience
0,CMP1018,Always-On Promo 19,Meta Ads,Lead Generation,2025-07-09,84765.97,2025-09-12,25-34
1,CMP1045,Monsoon Promo 46,TikTok,Brand Awareness,2024-07-05,201851.99,2024-09-13,55+
2,CMP1047,Always-On Retargeting 48,YouTube,Conversions,2024-03-27,74545.09,2024-04-24,35-44
3,CMP1089,Always-On Awareness 90,LinkedIn,Lead Generation,2024-12-08,214875.41,2025-02-04,18-24
4,CMP1004,Festive Acquisition 5,YouTube,Conversions,2024-10-04,216529.45,2024-10-18,55+
...,...,...,...,...,...,...,...,...
118,CMP1106,New Year Awareness 107,TikTok,Conversions,2025-02-17,81718.48,2025-05-16,55+
119,CMP1014,Diwali Awareness 15,YouTube,Traffic,2024-06-22,101102.23,2024-07-28,18-24
120,CMP1092,Monsoon Awareness 93,Instagram,Lead Generation,2024-06-18,153240.63,2024-07-21,35-44
121,CMP1051,New Year Acquisition 52,Meta Ads,Conversions,2024-04-09,55253.46,2024-06-16,45-54
122,CMP1102,Monsoon Retargeting 103,YouTube,Brand Awareness,2024-03-05,198604.10,2024-05-28,18-24

In [33]:
customers = pd.read_excel(file, sheet_name = 'Customers')
customers

     Customer_ID  Age  Gender       City Customer_Segment Signup_Date
0      CUS103567   21  Female      Delhi        Returning  2023-03-10
1      CUS101322   53  Female       Pune              New  2024-05-10
2      CUS107134   20    Male       Pune        Returning  2023-08-26
3      CUS102407   64  Female    Chennai              New  2024-02-13
4      CUS107131   22  Female      Delhi              New  2023-03-07
...          ...  ...     ...        ...              ...         ...
8195   CUS105734   35    Male    Chennai              New  2024-04-12
8196   CUS105191   54    Male  Hyderabad            Loyal  2025-05-26
8197   CUS105390   18    Male       Pune              New  2023-05-07
8198   CUS100860   25  Female    Chennai            Loyal  2023-11-12
8199   CUS107270   24   Other    Kolkata              New  2024-09-05

[8200 rows x 6 columns]

In [34]:
# Identifying Duplicate Records

customers.duplicated().sum()

np.int64(200)

In [35]:
# Droping Duplicate Values
customers = customers.drop_duplicates()
customers

     Customer_ID  Age  Gender       City Customer_Segment Signup_Date
0      CUS103567   21  Female      Delhi        Returning  2023-03-10
1      CUS101322   53  Female       Pune              New  2024-05-10
2      CUS107134   20    Male       Pune        Returning  2023-08-26
3      CUS102407   64  Female    Chennai              New  2024-02-13
4      CUS107131   22  Female      Delhi              New  2023-03-07
...          ...  ...     ...        ...              ...         ...
8195   CUS105734   35    Male    Chennai              New  2024-04-12
8196   CUS105191   54    Male  Hyderabad            Loyal  2025-05-26
8197   CUS105390   18    Male       Pune              New  2023-05-07
8198   CUS100860   25  Female    Chennai            Loyal  2023-11-12
8199   CUS107270   24   Other    Kolkata              New  2024-09-05

[8000 rows x 6 columns]

In [40]:
# Identifying missing values

customers.isnull().sum()

Customer_ID         0
Age                 0
Gender              0
City                0
Customer_Segment    0
Signup_Date         0
dtype: int64

In [41]:
# Handiling missing values

customers['Gender'] = customers['Gender'].fillna(customers['Gender'].mode()[0])

customers['City'] = customers['City'].fillna(customers['City'].mode()[0])

customers['Customer_Segment'] = customers['Customer_Segment'].fillna(customers['Customer_Segment'].mode()[0])
customers

C:\Users\deeli\AppData\Local\Temp\ipykernel_10044\1127730876.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['Gender'] = customers['Gender'].fillna(customers['Gender'].mode()[0])
C:\Users\deeli\AppData\Local\Temp\ipykernel_10044\1127730876.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['City'] = customers['City'].fillna(customers['City'].mode()[0])
C:\Users\deeli\AppData\Local\Temp\ipykernel_10044\1127730876.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['Customer_Segment'] = customers['Customer_Segment'].fillna(customers['Customer_Segment'].mode()[0])

     Customer_ID  Age  Gender       City Customer_Segment Signup_Date
0      CUS103567   21  Female      Delhi        Returning  2023-03-10
1      CUS101322   53  Female       Pune              New  2024-05-10
2      CUS107134   20    Male       Pune        Returning  2023-08-26
3      CUS102407   64  Female    Chennai              New  2024-02-13
4      CUS107131   22  Female      Delhi              New  2023-03-07
...          ...  ...     ...        ...              ...         ...
8195   CUS105734   35    Male    Chennai              New  2024-04-12
8196   CUS105191   54    Male  Hyderabad            Loyal  2025-05-26
8197   CUS105390   18    Male       Pune              New  2023-05-07
8198   CUS100860   25  Female    Chennai            Loyal  2023-11-12
8199   CUS107270   24   Other    Kolkata              New  2024-09-05

[8000 rows x 6 columns]

In [43]:
# Converting Dates into DateTime
customers['Signup_Date'] = pd.to_datetime(customers['Signup_Date'])
customers

C:\Users\deeli\AppData\Local\Temp\ipykernel_10044\804440380.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['Signup_Date'] = pd.to_datetime(customers['Signup_Date'])

     Customer_ID  Age  Gender       City Customer_Segment Signup_Date
0      CUS103567   21  Female      Delhi        Returning  2023-03-10
1      CUS101322   53  Female       Pune              New  2024-05-10
2      CUS107134   20    Male       Pune        Returning  2023-08-26
3      CUS102407   64  Female    Chennai              New  2024-02-13
4      CUS107131   22  Female      Delhi              New  2023-03-07
...          ...  ...     ...        ...              ...         ...
8195   CUS105734   35    Male    Chennai              New  2024-04-12
8196   CUS105191   54    Male  Hyderabad            Loyal  2025-05-26
8197   CUS105390   18    Male       Pune              New  2023-05-07
8198   CUS100860   25  Female    Chennai            Loyal  2023-11-12
8199   CUS107270   24   Other    Kolkata              New  2024-09-05

[8000 rows x 6 columns]

In [44]:
performance = pd.read_excel(file, sheet_name = 'Campaign_Performance')
performance

,Record_ID,Campaign_ID,Customer_ID,Date,Impressions,Clicks,Conversions,Spend,Revenue,Device,Audience_Type,CTR_Pct,Conversion_Rate_Pct,ROAS
0,REC1026923,CMP1056,CUS107401,2024-01-17,86866,8186.0,1146,41553.97,1630719.38,Mobile,Lookalike,9.42,14.00,39.24
1,REC1003242,CMP1112,CUS104665,2024-01-21,21941,2584.0,125,29736.00,116159.99,Desktop,Prospecting,11.78,4.84,3.91
2,REC1006988,CMP1101,CUS107305,2025-10-01,70836,3445.0,193,23985.62,79987.72,Mobile,Lookalike,4.86,5.60,3.33
3,REC1018735,CMP1054,CUS101539,2025-04-06,81225,9550.0,143,15074.59,98607.12,Tablet,Prospecting,11.76,1.50,6.54
4,REC1006133,CMP1008,CUS100093,2024-12-21,42736,2190.0,103,39385.83,85170.78,Desktop,Lookalike,5.12,4.70,2.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36220,REC1016850,CMP1034,CUS102978,2025-05-27,12716,1262.0,206,18171.60,104293.69,Mobile,Prospecting,9.92,16.32,5.74
36221,REC1006265,CMP1022,CUS106424,2024-10-23,30820,3175.0,268,41532.29,104297.49,Tablet,Prospecting,10.30,8.44,2.51
36222,REC1011284,CMP1113,CUS105981,2024-12-10,48119,4059.0,663,13651.51,594406.66,Desktop,Retargeting,8.44,16.33,43.54
36223,REC1000860,CMP1117,CUS100798,2024-07-30,7069,580.0,31,8740.70,38086.97,Desktop,Prospecting,8.20,5.34,4.36
36224,REC1015795,CMP1015,CUS101751,2025-05-02,11714,691.0,93,5494.65,45309.98,Mobile,Prospecting,5.90,13.46,8.25

In [45]:
# Identifying Duplicate Values

performance.duplicated().sum()

np.int64(1225)

In [46]:
# Removing Duplicate Values

performance = performance.drop_duplicates()
performance

,Record_ID,Campaign_ID,Customer_ID,Date,Impressions,Clicks,Conversions,Spend,Revenue,Device,Audience_Type,CTR_Pct,Conversion_Rate_Pct,ROAS
0,REC1026923,CMP1056,CUS107401,2024-01-17,86866,8186.0,1146,41553.97,1630719.38,Mobile,Lookalike,9.42,14.00,39.24
1,REC1003242,CMP1112,CUS104665,2024-01-21,21941,2584.0,125,29736.00,116159.99,Desktop,Prospecting,11.78,4.84,3.91
2,REC1006988,CMP1101,CUS107305,2025-10-01,70836,3445.0,193,23985.62,79987.72,Mobile,Lookalike,4.86,5.60,3.33
3,REC1018735,CMP1054,CUS101539,2025-04-06,81225,9550.0,143,15074.59,98607.12,Tablet,Prospecting,11.76,1.50,6.54
4,REC1006133,CMP1008,CUS100093,2024-12-21,42736,2190.0,103,39385.83,85170.78,Desktop,Lookalike,5.12,4.70,2.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36220,REC1016850,CMP1034,CUS102978,2025-05-27,12716,1262.0,206,18171.60,104293.69,Mobile,Prospecting,9.92,16.32,5.74
36221,REC1006265,CMP1022,CUS106424,2024-10-23,30820,3175.0,268,41532.29,104297.49,Tablet,Prospecting,10.30,8.44,2.51
36222,REC1011284,CMP1113,CUS105981,2024-12-10,48119,4059.0,663,13651.51,594406.66,Desktop,Retargeting,8.44,16.33,43.54
36223,REC1000860,CMP1117,CUS100798,2024-07-30,7069,580.0,31,8740.70,38086.97,Desktop,Prospecting,8.20,5.34,4.36
36224,REC1015795,CMP1015,CUS101751,2025-05-02,11714,691.0,93,5494.65,45309.98,Mobile,Prospecting,5.90,13.46,8.25

In [47]:
performance.duplicated().sum()

np.int64(0)

In [48]:
# Identifying missing values

performance.isnull().sum()

Record_ID                0
Campaign_ID              0
Customer_ID              0
Date                     0
Impressions              0
Clicks                 350
Conversions              0
Spend                  350
Revenue                350
Device                 350
Audience_Type          350
CTR_Pct                  0
Conversion_Rate_Pct      0
ROAS                     0
dtype: int64

In [49]:
# Handiling missing values

performance['Clicks'] = performance['Clicks'].fillna(performance['Clicks'].median())

performance['Spend'] = performance['Spend'].fillna(performance['Spend'].median())

performance['Revenue'] = performance['Revenue'].fillna(performance['Revenue'].median())

performance['Device'] = performance['Device'].fillna(performance['Device'].mode()[0])

performance['Audience_Type'] = performance['Audience_Type'].fillna(performance['Audience_Type'].mode()[0])

performance

C:\Users\deeli\AppData\Local\Temp\ipykernel_10044\1743623955.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance['Clicks'] = performance['Clicks'].fillna(performance['Clicks'].median())
C:\Users\deeli\AppData\Local\Temp\ipykernel_10044\1743623955.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance['Spend'] = performance['Spend'].fillna(performance['Spend'].median())
C:\Users\deeli\AppData\Local\Temp\ipykernel_10044\1743623955.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance['Revenue'] = performance['Revenue'].fillna(performance['Revenue'].median())
C:\Users\deeli\AppData\Local\Temp\ipykernel_10044\1743623955.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance['Device'] = performance['Device'].fillna(performance['Device'].mode()[0])
C:\Users\deeli\AppData\Local\Temp\ipykernel_10044\1743623955.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance['Audience_Type'] = performance['Audience_Type'].fillna(performance['Audience_Type'].mode()[0])

,Record_ID,Campaign_ID,Customer_ID,Date,Impressions,Clicks,Conversions,Spend,Revenue,Device,Audience_Type,CTR_Pct,Conversion_Rate_Pct,ROAS
0,REC1026923,CMP1056,CUS107401,2024-01-17,86866,8186.0,1146,41553.97,1630719.38,Mobile,Lookalike,9.42,14.00,39.24
1,REC1003242,CMP1112,CUS104665,2024-01-21,21941,2584.0,125,29736.00,116159.99,Desktop,Prospecting,11.78,4.84,3.91
2,REC1006988,CMP1101,CUS107305,2025-10-01,70836,3445.0,193,23985.62,79987.72,Mobile,Lookalike,4.86,5.60,3.33
3,REC1018735,CMP1054,CUS101539,2025-04-06,81225,9550.0,143,15074.59,98607.12,Tablet,Prospecting,11.76,1.50,6.54
4,REC1006133,CMP1008,CUS100093,2024-12-21,42736,2190.0,103,39385.83,85170.78,Desktop,Lookalike,5.12,4.70,2.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36220,REC1016850,CMP1034,CUS102978,2025-05-27,12716,1262.0,206,18171.60,104293.69,Mobile,Prospecting,9.92,16.32,5.74
36221,REC1006265,CMP1022,CUS106424,2024-10-23,30820,3175.0,268,41532.29,104297.49,Tablet,Prospecting,10.30,8.44,2.51
36222,REC1011284,CMP1113,CUS105981,2024-12-10,48119,4059.0,663,13651.51,594406.66,Desktop,Retargeting,8.44,16.33,43.54
36223,REC1000860,CMP1117,CUS100798,2024-07-30,7069,580.0,31,8740.70,38086.97,Desktop,Prospecting,8.20,5.34,4.36
36224,REC1015795,CMP1015,CUS101751,2025-05-02,11714,691.0,93,5494.65,45309.98,Mobile,Prospecting,5.90,13.46,8.25

In [50]:
# Converting Date

performance['Date'] = pd.to_datetime(performance['Date']).dt.date
performance

C:\Users\deeli\AppData\Local\Temp\ipykernel_10044\2749119023.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance['Date'] = pd.to_datetime(performance['Date']).dt.date

,Record_ID,Campaign_ID,Customer_ID,Date,Impressions,Clicks,Conversions,Spend,Revenue,Device,Audience_Type,CTR_Pct,Conversion_Rate_Pct,ROAS
0,REC1026923,CMP1056,CUS107401,2024-01-17,86866,8186.0,1146,41553.97,1630719.38,Mobile,Lookalike,9.42,14.00,39.24
1,REC1003242,CMP1112,CUS104665,2024-01-21,21941,2584.0,125,29736.00,116159.99,Desktop,Prospecting,11.78,4.84,3.91
2,REC1006988,CMP1101,CUS107305,2025-10-01,70836,3445.0,193,23985.62,79987.72,Mobile,Lookalike,4.86,5.60,3.33
3,REC1018735,CMP1054,CUS101539,2025-04-06,81225,9550.0,143,15074.59,98607.12,Tablet,Prospecting,11.76,1.50,6.54
4,REC1006133,CMP1008,CUS100093,2024-12-21,42736,2190.0,103,39385.83,85170.78,Desktop,Lookalike,5.12,4.70,2.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36220,REC1016850,CMP1034,CUS102978,2025-05-27,12716,1262.0,206,18171.60,104293.69,Mobile,Prospecting,9.92,16.32,5.74
36221,REC1006265,CMP1022,CUS106424,2024-10-23,30820,3175.0,268,41532.29,104297.49,Tablet,Prospecting,10.30,8.44,2.51
36222,REC1011284,CMP1113,CUS105981,2024-12-10,48119,4059.0,663,13651.51,594406.66,Desktop,Retargeting,8.44,16.33,43.54
36223,REC1000860,CMP1117,CUS100798,2024-07-30,7069,580.0,31,8740.70,38086.97,Desktop,Prospecting,8.20,5.34,4.36
36224,REC1015795,CMP1015,CUS101751,2025-05-02,11714,691.0,93,5494.65,45309.98,Mobile,Prospecting,5.90,13.46,8.25

In [52]:
# Saving files into CSV

campaigns.to_csv("cleaned_campaigns.csv", index = False)
customers.to_csv("cleaned_customers.csv", index = False)
performance.to_csv("cleaned_performance.csv", index = False)